In [1]:
import torch
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.2925, -0.8835, -2.2935], requires_grad=True)


In [2]:
y = x+2
print(y)

tensor([ 0.7075,  1.1165, -0.2935], grad_fn=<AddBackward0>)


In [3]:
z = y*y*2
print(z)

tensor([1.0012, 2.4929, 0.1723], grad_fn=<MulBackward0>)


In [4]:
z = z.mean()
print(z)

tensor(1.2222, grad_fn=<MeanBackward0>)


In [5]:
z.backward()
print(x.grad)

tensor([ 0.9434,  1.4886, -0.3914])
